=== apache/jmeter/bin/users.dtd
<!ELEMENT allthreads (thread+)>
<!ATTLIST thread
>
<!ELEMENT thread (parameter+)>
<!ATTLIST parameter
>
<!ELEMENT parameter (paramname,paramvalue) >
<!ELEMENT paramname   (#PCDATA)   >
<!ELEMENT paramvalue  (#PCDATA)  >

=== apache/jmeter/bin/users.xml
<?xml version="1.0"?>
<!DOCTYPE allthreads SYSTEM "users.dtd">

	<!-- all users, uses round robin selection -->
	<allthreads>
	        <!-- unique parameters for each individual thread (ie user) -->

		<thread>
			<parameter>
                             <paramname>user_id</paramname>
                             <paramvalue>dduck</paramvalue>
                        </parameter>
			<parameter>
                             <paramname>password</paramname>
                             <paramvalue>quack</paramvalue>
                        </parameter>
		</thread>
		<thread>
			<parameter>
                             <paramname>user_id</paramname>
                             <paramvalue>mmouse</paramvalue>
                        </parameter>
			<parameter>
                             <paramname>password</paramname>
                             <paramvalue>squeak</paramvalue>
                        </parameter>
		</thread>
		<thread>
			<parameter>
                             <paramname>user_id</paramname>
                             <paramvalue>bbunney</paramvalue>
                        </parameter>
			<parameter>
                             <paramname>password</paramname>
                             <paramvalue>carrot</paramvalue>
                        </parameter>
			<parameter>
                             <paramname>manager</paramname>
                             <paramvalue>yes</paramvalue>
                        </parameter>
		</thread>
	</allthreads>
